wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
    priority: 100
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2
    priority: 50
  reboot_timeout: "2h"
  fast_connect: false